### ISSUE TITLE
PHP 7 Features

### ISSUE THREAD

**Issue by gerardroche** [gerardroche/sublime-php-grammar#91]
- [x] #64 Support for PHP 7 null coalescing operator
- [x] #68 Support for PHP 5.6 exponentiation operator
- [x] #69 Support for PHP 7 spaceship operator
- [x] #70 Scalar type declarations enhancement php7 
- [ ] #71 Return type declarations enhancement php7 
- [ ] #73 Anonymous classes enhancement php7 
- [x] #74 Support for PHP 7 unicode codepoint escape syntax
- [ ] #79 Group use declarations enhancement php7 
- [ ] #81 Generator delegation enhancement php7 
- [x] #82 Remove support for Extensions and SAPIs removed in PHP 7
- [x] #82 Support for new PHP 7 constants
- [x] #82 Support for new PHP 7 functions
- [x] #82, #78 Support for new PHP 7 classes
